### PR TITLE
WYSIWYG for admin news and simpler race theming.

### PR DESCRIPTION
**Pull request by aaronjewell**
Carryover from #347 under organization so build checks and run.

### CODE REVIEW

**Comment by modmoto** [comment]
and the deployment worked =D

https://admin-news-content.ui.w3champions.com

**Comment by aaronjewell** [comment]
🕺 🎈 🎉

**Comment by modmoto** [comment]
We should wait until the launcher is released with the PR you made there. Then I am happy to do that =D

**Comment by aaronjewell** [comment]
@modmoto - Should be good after the last couple releases!

**Comment by modmoto** [comment]
ah jeah right, you want to resolve the merge conflict and merge from master again? Then we can just release. Backend is already out and fine, right?

**Comment by aaronjewell** [comment]
Yep! Uses existing endpoints for news item with same data structure. Only potential defect that might arise is a race theme colored element being incorrect due to the theming enhancements. The ability for the launcher to display HTML is live.

**Pull request merged**
