### PR TITLE
improved padding on match details view card

### PR DESCRIPTION
**Pull request by elevchyt**
Simple UI improvement I did to play around the project and learn its structure for future issues.

before
after

### CODE REVIEW

**Comment by gustav87** [comment]
Hi, thanks for the contribution! I agree it needs some padding, but pa-8 seems excessive.

**Comment by elevchyt** [comment]
> Hi, thanks for the contribution! I agree it needs some padding, but pa-8 seems excessive.

No problem, just pushed a new commit that sets it to 6.

**Comment by gustav87** [comment]
image
Ideally these should be the same, I think

**Comment by gustav87** [comment]
So you may only need to add padding to the bottom

**Comment by elevchyt** [comment]
I see, thought the names should have some more padding since their container has some padding by itself.
Added padding bottom of 5 so that it's equal to the top side padding.

**Review by gustav87 — APPROVED** [review]

**Comment by gustav87** [comment]
Nice, thank you for the contribution!

**Pull request merged**
