### PR TITLE
Redesign main navigation bar & bugfix on /tournaments page

### PR DESCRIPTION
**Pull request by amacado**
- [x] minor code refactorings
- [x] redesign main navigation (for mobile) #407
- [x] code refactoring and component separation

Here are some previous for the updated navbar design:
<table>
<tr>
<td>

image
</td>
<td>

image
</td>
<td>

image

</td>
<td>

image
</td>
</tr>
</table>

And here is a preview for the (partly) fixed bug on the tournaments page:
<table>
<tr>
<td width="30%">

image
image

</td>
<td>

Fixed multiple bugs on [/tournaments page](https://www.w3champions.com/tournaments) which causes the bracked to not show up:

- Duplicate `:keys`
- Invalid access on undefined properties `round.dimensions`
- There is still a bug, described in #439 (but I assume this should be in a new pr)

</td>
</tr>
</table

### CODE REVIEW

**Comment by HooK2000** [comment]
I might be missing something here, but vuetify provides the breakpoints as booleans (`$vuetify.breakpoint`), right?

So I'd think a cleaner way than hiding stuff with css would be to actually dismount the components/DOM elements with something like `v-if="$vuetify.breakpoint.lgAndUp"` (desktop) and `v-if="$vuetify.breakpoint.mdAndDown"` (mobile).

**Comment by amacado** [comment]
@HooK2000 you could do that, yeah.. I think it's more a "what do you prefer" decision.. I usually prefer the css solution over the javascript solution for three reasons
- If js is disabled in the browser it still works
- css classes are "more common" and "more known" (personal experience)
- js DOM manipulation probably takes more time than using css (not 100% sure about that)

Is it more readable using `v-if="$vuetify.breakpoint.lgAndUp"`? Maybe. Hard to tell and more a personal preference or?

**Comment by HooK2000** [comment]
@amacado Ok that's fair, I just assumed that this was "the way to go" with vue/vuetify. I'm just a big fan of keeping the DOM clean ;)

**Comment by amacado** [comment]
I haven't found a "best practice" by vuetify, but when they talk about the requirement of visibility changes based on screen sizes they introduce the "css class" approach. See here https://vuetifyjs.com/en/styles/display/#visibility

**Pull request merged**
