### PR TITLE
hiding region selector for season 6 and beyond

### PR DESCRIPTION
**Pull request by Raswanson01**
Added a v-if to the gateway-select component to hide for seasons 6 and later

### CODE REVIEW

**Comment by Raswanson01** [comment]
#402

**Comment by Raswanson01** [comment]
I didn't commit anything for the profiles or statistics because the page will break for American players. The page will default to America stats, of which there are none, with no selector to get back to Europe. I will look into seeing if I can set the default locale to Europe for season 6+ as well.

**Comment by Raswanson01** [comment]
Actually, this is the case on the rankings page right now, so I'll close this and reopen it once I've figured that out.

**Comment by Raswanson01** [comment]
#432 is the new PR for this

**Comment by Cepheid-UK** [comment]
ty @Raswanson01 this is on the live website now. Sorry for the delay.

**Pull request closed without merging**
