### PR TITLE
fix flags colors

### PR DESCRIPTION
**Pull request by AucT**
fixes colors of flags according to wikipedia.

p.s. would be nice to replace it with standard 3x2 size, because circle size is meh for some flags like Great Britain.
ps. Your flag for South Korea has wrong shape (I didn't touch shape and leaved as it is).
ps. I didn't touch PT flag as I think it is Brazil flag and not Portugal.

### CODE REVIEW

**Comment by AucT** [comment]
I will suggest you use good trusted library for flags like this https://github.com/lipis/flag-icons

**Comment by alocate** [comment]
@AucT that's a name I'm happily surprised to see here :) been using your inventory hotkeys software for about 10 years, and constantly recommend it to other people :P would you be interested in joining the W3C discord? https://discord.gg/AWYHRakU
recently, we've actually been talking about integrating your hotkeys software into our new launcher, and maybe you could provide some guidance!

**Comment by AucT** [comment]
@alocate create thread about hotkeys, I can tell a brief info about hotkeys I've made.

**Comment by gustav87** [comment]
Hi, thanks for the contribution! We're actually using `flag-icons` in our new launcher project. For other flags on the website we use vue-country-flag, if I remember correctly. Merged!

**Comment by AucT** [comment]
Thanks. These "bad" color flags are on your website https://www.w3champions.com/ on the right language chooser.
Other flags on loading screen, etc are good.

**Comment by gustav87** [comment]
It's updated in the test environment https://test.w3champions.com/ now. And now I'm deploying to prod.

**Comment by gustav87** [comment]
Hey @AucT, are you on our Discord now? We would love to have a chat.

**Comment by AucT** [comment]
@gustav87 yes, I'm on discord

**Comment by gustav87** [comment]
What's your nickname?

**Comment by AucT** [comment]
nicelydone7

**Pull request merged**
