### PR TITLE
Add map filter to matches.

### PR DESCRIPTION
**Pull request by aaronjewell**
The match select uses a hard-coded list of maps. This might be
more appropriate to get from a API. I'm not 100% sure that the list
hard-coded in this commit is the most correct list of maps, but it
seems to be pretty close.

Front end implementation to address part of #277 
Companion back end PR at w3champions/w3champions-statistic-service#108

### CODE REVIEW

**Comment by Cepheid-UK** [comment]
We really can't do that maps() function like that. It really has to be dynamically generated.

Look at this for some guidance:

https://github.com/w3champions/w3champions-ui/blob/2ea079324634d70161abcf6d608c6e6064dc423d/src/store/overallStats/index.ts#L58

**Comment by aaronjewell** [comment]
I thought that might be the case. It now pulls the list of games by mode, and for finished matches it reduces the maps from all seasons, while ongoing matches are shown only current season maps played.

There are currently two outstanding issues, the first is that in some cases maps are translated into the same label: "Autumn Leaves", and there is at least one translation that doesn't exist for "lastrefuge.anon". That one will also need to be handled special because of the "." character in the name, I believe, will conflict with the translation method, since it uses dot notation for nesting. I haven't identified if there is a way to escape it in the translation module.

To handle the same name, I was considering appending the map key in parentheses on only duplicate labels, but the UX seems poor. I would love feedback on alternative ideas!

**Comment by Cepheid-UK** [comment]
> "lastrefuge.anon"

That was actually a mistake during the S4 reset, we accidentally named one of the maps with a . instead of a _.

I believe the map file was renamed and any old entries in the db for "lastrefuge.anon" were migrated to the "lastrefuge_anon"

I don't _think_ that "lastrefuge.anon" will ever appear, and that translation should really be removed, but I'm not certain.

**Comment by aaronjewell** [comment]
Great! I was using the test dump, so that makes sense. Perhaps putting `(Oct 20)` on the end of the Autumn Leaves translation for autumnsleaves_201016 is a decent tradeoff then since it's limited in scope to a single map?

**Comment by Cepheid-UK** [comment]
Just bumping this because I've totally forgotten where this got to, is this ready for merge?

**Comment by aaronjewell** [comment]
No worries! This doesn't solve the Autumn Leaves dilemma, but that's an existing data defect. This is ready, but needs the accompanying BE PR https://github.com/w3champions/website-backend/pull/108

**Pull request merged**
