### PR TITLE
WYSIWYG for admin news and simpler race theming.

### PR DESCRIPTION
**Pull request by aaronjewell**
The current editor I believe supports Markdown, submitting this PR as a possible alternative. This also includes some theme enhancements to make future styling simpler and support more components "out of the box" from Vuetify.

Assuming I understand the Azure auto-deploy correctly... [PR Deployment](https://pr.add-admin-news-content.ui.w3champions.com)

- Add WYSIWYG editor to the admin news create/edit
- Use variables to theme Vuetify. Enhance theme switcher using CSS variables + theme SCSS variables to allow for variations of dark/light based on race. Greatly reduces the number of color overrides and `!important` tags in the styles. Also allows more components to be themed automatically "out of the box."

Minor tweaks
- Some tab navigation was missing "exact" attributes to properly highlight selected
- Switched some inline transparent styles to theme classes.

wysiwg-editor

### CODE REVIEW

**Comment by aaronjewell** [comment]
Implements #295 with an alternative to markdown editing.

**Comment by modmoto** [comment]
Pretty cool =D

Regarding the PR: It looks like the mechanism does not work for PRs outside the org, because you are missing secrets in the build. That is why the build is also red. I can just add you as a new-dev to the team and you push the branch to the repo directly?

**Comment by modmoto** [comment]
Also: does this create md content? Because the launcher treats the news as md content and renders it in html. So it would be good to check if we need changes in the launcher for that aswell.

**Comment by modmoto** [comment]
ok, i added you with a new-dev role. That should make website and website-backend writable for you. 

Regarding the md in the launcher: This is also just a div with content. I guess we can use the same render methoid like on the website, as it is an electron app. Building the launcher is somewhat tricky, so if you have issues with that, just reach out. I could also do it, if it is just about adding a npm install and a new component. But we can check that later.

**Comment by modmoto** [comment]
I am not emotionally attached to md, we just had it in place of a WYSIWYG  for poor people. But the news still have to show up in the launcher somewhat properly.

**Comment by aaronjewell** [comment]
I like the idea of the launcher being able to handle markdown and html at the same time. We can leave the vue-markdown component, and v-if/else it with a regular v-html div. Should be easy enough to check. I'm thinking looking at the starting and ending character of the whitespace trimmed news content item and checking for `<` and `>`. That should be enough to distinguish it from md.

**Comment by aaronjewell** [comment]
PR for launcher update at w3champions/launcher#80

**Comment by aaronjewell** [comment]
Moving PR to organization account #351.

**Pull request closed without merging**
