### PR TITLE
WIP Add localization to the website

### PR DESCRIPTION
**Pull request by RickyMarou**
🚧 Work in progress

✅ Pulling data from the Google Sheet  
✅ Injecting it to the `vue-i18n` as default/fallback values  
IN PROGRESS: 🕵️ Check all the strings in the website (😭😭😭)
TODO: 💄 Move the language selection dropdown to it's own component
TODO: 🕵️ Thorough QA

## Progress tracking:

```
src/views
├── Admin.vue ✅
├── Faq.vue ✅
├── GettingStarted.vue ✅
├── Home.vue ✅
├── Imprint.vue ✅
├── Login.vue ✅
├── MatchDetail.vue ✅
├── Matches.vue ✅
├── OverallStatistics.vue ✅
├── Player.vue ✅
├── Rankings.vue ✅
└── Tournaments.vue ✅



src/components
├── admin ✅
│   ├── AdminBannedPlayers.vue ✅
│   ├── AdminLoadingScreenTips.vue ✅
│   ├── AdminNavigation.vue ✅
│   └── AdminNewsForLauncher.vue TODO
├── clans ✅
│   ├── AcceptInvitePanel.vue ✅
│   ├── ClanCreationPanel.vue ✅ 
│   ├── ClanOverview.vue ✅
│   ├── ClanRoleIcon.vue ✅
│   ├── DeleteClanModal.vue ✅
│   ├── InvitePlayerModal.vue ✅
│   ├── LeaveClanModal.vue ✅
│   ├── MemberManagementMenu.vue ✅
│   └── PendingInvitesPanel.vue ✅
├── common ✅
│   ├── CountryFlagExtended.vue ✅
│   ├── GameModeSelect.vue ✅
│   ├── GatewaySelect.vue ✅
│   ├── LocaleIcon.vue ✅
│   ├── SocialBox.vue ✅
│   └── SupportBox.vue ✅
├── ladder ✅
│   ├── CountryRankingsGrid.vue ✅
│   ├── LeagueIcon.vue ✅
│   ├── PlayerRankInfo.vue ✅
│   ├── RankingsGrid.vue ✅
│   ├── RankingsRaceDistribution.vue ✅
│   └── SwordIcon.vue ✅
├── match-details ✅
│   ├── HeroIcon.vue ✅
│   ├── HeroPicture.vue ✅
│   ├── MatchDetailHeroRow.vue ✅
│   ├── MatchHiglights.vue ✅
│   └── PlayerPerformanceOnMatch.vue ✅
├── matches
│   ├── HostIcon.vue ✅
│   ├── MatchesGrid.vue ✅
│   ├── MatchesStatusSelect.vue ✅
│   ├── PlayerIcon.vue ✅
│   ├── PlayerMatchInfo.vue ✅
│   ├── StreamedMatchInfo.vue ✅
│   ├── StreamedMatchPlayerInfo.vue ✅
│   ├── TeamMatchInfo.vue ✅
│   └── TopOngoingMatchesWithStreams.vue ✅
├── overal-statistics
│   ├── AmountPerDayChart.vue
│   ├── AmountPerGatewayPerDayChart.vue
│   ├── BarChart.vue
│   ├── GameLengthChart.vue
│   ├── HeroPictureSelect.vue
│   ├── HeroWinrate.vue
│   ├── LineChart.vue
│   ├── MapsPerSeasonChart.vue
│   ├── MmrDistributionChart.vue
│   ├── MultipleAmountPerDayChart.vue
│   ├── PlayedHeroesChart.vue
│   ├── PopularGameTimeChart.vue
│   ├── RaceToMapStat.vue
│   └── tabs
│       ├── HeroTab.vue ✅
│       ├── MmrDistributionTab.vue ✅
│       ├── PlayerActivityTab.vue ✅ (the v-select component uses enum ids as labels so did not translate the word "All") 
│       └── WinratesTab.vue
├── player
│   ├── ModeStatsGrid.vue
│   ├── PlayerAvatar.vue
│   ├── PlayerLeague.vue
│   ├── PlayerMmrRpTimelineChart.vue
│   ├── PlayerStatsRaceVersusRaceOnMap.vue
│   ├── PlayerStatsRaceVersusRaceOnMapTableCell.vue
│   ├── RaceIcon.vue
│   ├── RecentPerformance.vue
│   ├── SeasonBadge.vue
│   ├── TrovoIcon.vue
│   └── tabs
│       ├── PlayerArrangedTeamsTab.vue
│       ├── PlayerMatchesTab.vue
│       ├── PlayerProfileTab.vue
│       └── PlayerStatisticTab.vue
└── tournaments
    ├── TournamentBracket.vue
    ├── TournamentMatch.vue
    ├── TournamentMatchUpdate.vue
    ├── TournamentRoundConnector.vue
    ├── TournamentSelect.vue
    ├── TournamentStraightOpenConnector.vue
    ├── TournamentStraightOpenDownConnector.vue
    └── TournamentYConnector.vue

```

### CODE REVIEW

**Comment by RickyMarou** [comment]
@modmoto you can make your PR to this branch.
I'll have another look when you submit but from what I remember last time I looked at the branch we can keep it like that and i can add fingerprinting to the filename to do cachebusting.

**Comment by modmoto** [comment]
jeah, just building is fine, I will take a look at the release how we can do the cache whipe from azure.

**Comment by modmoto** [comment]
btw, I added the possibility to deploy on a different pr-environment, if you like to have the website deployed with the translations somewhere else before we go to test. I added the explanation in the repo

**Comment by modmoto** [comment]
hey, i fixed the language selector and made it a little bit more in line with the other services that we have. I deployed it real quick to here, seems good so far =)

https://locale-test.ui.w3champions.com

**Comment by RickyMarou** [comment]
Thanks a lot for the contribution @modmoto 
I'll close and re-open the PR with the DEPLOY prefix once it's ready to QA.

About the cachebusting maybe you can try what i suggested, i noticed than in your branch you wrote to a file called `translate.js`. I think fingerprinting it should do the trick: everytime we generate the file, generate a hash from the text content and add that to the end of the file (`translate.${hash}.js`).

**Comment by RickyMarou** [comment]
This PR still has quite some way to go but yeah it's looking good so far 👍 
I can only commit a few hours a week right now but at some points in the next weeks i'll be able to commit more time and that's when i'll focus on shipping this

**Comment by modmoto** [comment]
right now it is bundles with the other js stuff and therefore is also invalidating the cash. I think that is good enough for now. With the new machine we should be able to handle the js upload. And then it is cashed in the browser aswell. The webpage is 136kb right now, lets see how big the translations get but I guess it is actually not that much to be relevant. Weirdly enough, the PR env is dead right now ^^ so I cant see how much it is with the translations together.

**Comment by RickyMarou** [comment]
yeah this is what i initially suggested. Just leave the setup like this, make sure to run the script *before* the build step and then it'll be included with the rest of the website 👍 

I'll close / re-open the branch with the deploy prefix once i'm done going through all the files

**Comment by modmoto** [comment]
Would you be fine if i renamed the branch into DEPLOY_locale? seeing it live would be cool, I guess. Will do some translation work myself today, think this is really a plus =)

I was thinking of adding a language detector of some sort aswell, if the user did not select a language yet.

**Pull request closed without merging**
