### PR TITLE
Merging with latest master, improving some translations

### PR DESCRIPTION
**Pull request by joleb**

### CODE REVIEW

**Comment by Cepheid-UK** [comment]
is this ready?

**Comment by joleb** [comment]
it should be ready, may try and verify yourself

**Comment by Cepheid-UK** [comment]
Great, I'll give it a bit of a check at earliest convenience and we can finally launch this bad boy.

**Comment by Cepheid-UK** [comment]
I realised this was actually a PR to the feature branch not master, so we can merge and check it on the feature branch.

**Pull request merged**
