### PR TITLE
added battleTagToName helper function to replace repeated code

### PR DESCRIPTION
**Pull request by elevchyt**
Created a helper function to separate the name from the battle tag.
Happy to move this to another file if `profile.ts` isn't ok.

### CODE REVIEW

**Comment by gustav87** [comment]
Are you not missing the imports for these functions?

**Comment by gustav87** [comment]
Are you on the W3Champions Discord by the way? I can assign you the staff role, so it's easier to communicate.

**Comment by elevchyt** [comment]
> Are you on the W3Champions Discord by the way? I can assign you the staff role, so it's easier to communicate.

Yeah, feel free to message me there, my name on the w3champions Discord is biskuit.

**Comment by elevchyt** [comment]
> Are you not missing the imports for these functions?

Apologies, fixed now.
By the way, do you think this type of helper function would be better to be in a mixin?

**Comment by gustav87** [comment]
Great. Did you test this locally as well?

**Comment by elevchyt** [comment]
> Great. Did you test this locally as well?

Yup!

**Comment by gustav87** [comment]
Make sure you run `yarn dprint` as well, to check formatting.

**Comment by gustav87** [comment]
I haven't added that to the PR pipeline yet, so you need to do it yourself.

**Review by gustav87 — APPROVED** [review]

**Comment by gustav87** [comment]
Nice, thank you! Merging.

**Pull request merged**
