### PR TITLE
Chart misc fixes

### PR DESCRIPTION
**Pull request by gustav87**

### CODE REVIEW

**Comment by gustav87** [comment]
@Rotzbua Hey, great work with the chart-js upgrade in https://github.com/w3champions/website/pull/628. I tried to do it once but couldn't figure out how to migrate without breaking stuff. I hope you don't mind, I added legends and a gradient fill, but you probably know more than me about chart-js by now so if you could review I'd be grateful!

**Comment by Rotzbua** [comment]
Sure I can help. However, I did the main part of the migration around New Year, so it's been a while.
Unfortunately, I was not able to migrate the gradient fill properly, so I removed it.

**Comment by gustav87** [comment]
No problem :) I added gradient and legends here. merging!

**Comment by Rotzbua** [comment]
Nice work 👍

**Pull request merged**
