### PR TITLE
removing an scss override that was causing v-btn to not show "current" state

### PR DESCRIPTION
**Pull request by cmavelis**
News carousel, nav tabs, etc.  Looking at the blame, @kato88 added this as a bulk change, so I expect it wasn't intentional.  If anyone knows of a button where we _don't_ want this, it would be good to know

Screen Shot 2021-01-30 at 12 50 29 PM
Screen Shot 2021-01-30 at 12 50 54 PM

### CODE REVIEW

**Comment by cmavelis** [comment]
see: https://vuetifyjs.com/en/components/carousels/
for default styling example

**Comment by modmoto** [comment]
ah you mean the grey outline? jeah cool, will merge

**Comment by modmoto** [comment]
released on prod, thanks =D

**Comment by cmavelis** [comment]
JOBS DONE

**Pull request merged**
