### PR TITLE
Upgrade to vue 3 try 3

### PR DESCRIPTION
**Pull request by gustav87**

### CODE REVIEW

**Comment by SergeyKhval** [comment]
@gustav87 I see a couple of attempts to migrate to Vue3 and Vuetify3. what help is needed to finish this migrations?

**Comment by gustav87** [comment]
> @gustav87 I see a couple of attempts to migrate to Vue3 and Vuetify3. what help is needed to finish this migrations?

Hi! There are quite a few issues related to Vuetify. Lots of styles missing. I don't remember exactly the next steps for this. I would love if we could pick it up again though.

I can solve all the merge conflicts so you can pull and check it out for yourself, if you're interested?

**Comment by SergeyKhval** [comment]
@gustav87 yeah, would be nice if you could resolve the conflicts. I might give it a shot to upgrade

**Comment by gustav87** [comment]
@SergeyKhval I've made a new branch with a minimally working state. There's a lot to work on! https://github.com/w3champions/website/pull/828

**Pull request closed without merging**
